---

app:
  port: 8000

database: 
  postgres_host: #db
  postgres_user: #PNgvMjSHKgcJRlvhnaEtyrHMNYDXvqDE
  postgres_password: #ufqAdXuPyXWHo2AyR7jxaj7dHrnWprLGBzDC4q43ZF9I3Ku
  postgres_db: #gorm
  postgres_ssl: #disable
  postgres_db_port: #5432

