log:
  level: INFO

entryPoints:
  web:
    # http
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: web-secure

  web-secure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "todd.develop@gmail.com"
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        entryPoint: web

http:
  routers:
    web-secure-router:
      rule: "Host(`e-comdata.ru`) || Host(`www.e-comdata.ru`)"
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: backend
      tls:
        certResolver: letsencrypt

  middlewares:
    csrf:
      headers:
        hostsProxyHeaders: ["X-CSRFToken"]

  services:
    backend:
      loadBalancer:
        servers:
          - url: http://backend:10000

providers:
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
