name: CI

on:
  push:
    branches:
      - master

# env:
  # REGISTRY: "registry.digitalocean.com/sandbox-registry"
  # IMAGE_NAME: "pocket-bot"
  # CONTAINER_NAME: "pocket"

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Reg.ru droplet via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |
            cd simple_api_go/
            git pull
            sudo ./scripts/build_prod.sh
            sudo ./script/up_prod.sh